return {
	"startup-nvim/startup.nvim",
	dependencies = { "nvim-telescope/telescope.nvim", "nvim-lua/plenary.nvim" },
	opts = {
		header = {
			type = "text",
			align = "center",
			fold_section = false,
			title = "Header",
			margin = 5,
			content = {
				"███╗   ██╗███████╗ ██████╗ ██╗   ██╗██╗███╗   ███╗",
				"████╗  ██║██╔════╝██╔═══██╗██║   ██║██║████╗ ████║",
				"██╔██╗ ██║█████╗  ██║   ██║██║   ██║██║██╔████╔██║",
				"██║╚██╗██║██╔══╝  ██║   ██║╚██╗ ██╔╝██║██║╚██╔╝██║",
				"██║ ╚████║███████╗╚██████╔╝ ╚████╔╝ ██║██║ ╚═╝ ██║",
				"╚═╝  ╚═══╝╚══════╝ ╚═════╝   ╚═══╝  ╚═╝╚═╝     ╚═╝",
			},
			highlight = "Statement",
			default_color = "",
			oldfiles_amount = 0,
		},
		body = {
			type = "mapping",
			align = "center",
			fold_section = false,
			title = "Actions",
			margin = 5,
			content = {
				{ " Find File", "Telescope find_files", "<leader>ff" },
				{ " Recent Files", "Telescope oldfiles", "<leader>fr" },
				{ " Find Word", "Telescope live_grep", "<leader>fg" },
				{ " New File", "lua require'startup'.new_file()", "<leader>nf" },
			},
			highlight = "String",
			default_color = "",
			oldfiles_amount = 0,
		},
		parts = { "header", "body" },
	},
}
