-- Improved syntax highlighting
return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	init = function()
		---@diagnostic disable-next-line: missing-fields
		require("nvim-treesitter").install({
			"asm",
			-- "bash",
			-- "c",
			-- "c_sharp",
			-- "cmake",
			-- "cpp",
			-- "css",
			"csv",
			"dockerfile",
			"doxygen",
			"editorconfig",
			"elixir",
			"fsharp",
			"gdscript",
			"gitattributes",
			"gitignore",
			-- "go",
			-- "gomod",
			-- "haskell",
			-- "html",
			-- "java",
			-- "javascript",
			-- "jsdoc",
			-- "json",
			"json5",
			-- "julia",
			"latex",
			"llvm",
			-- "lua",
			"make",
			-- "markdown",
			-- "markdown-inline",
			-- "ocaml",
			"powershell",
			-- "python",
			"ron",
			-- "rust",
			"sql",
			"toml",
			-- "typescript",
			-- "vim",
			-- "vimdoc",
			"vue",
			"wgsl",
			"wgsl_bevy",
			"xml",
			"yaml",
			"zig",
		})

		vim.treesitter.language.register("zenscript", "zenscript")
	end,
}
